services:
  janken:
    build: ./janken/
    container_name: janken_app
    ports:
      - "50000:5000"
    command: ["bash", "entrypoint.sh"]
  tutorial:
    build: ./tutorial/
    container_name: tutorial_app
    ports:
      - "50001:5000"
    command: ["flask", "run", "--host=0.0.0.0"]
  secure-janken:
    build: ./secure-janken/
    container_name: secure_janken_app
    ports:
      - "50002:5000"
    command: ["bash", "entrypoint.sh"]
